all_currencies_dict = {
                    "AED": "United Arab Emirates Dirham",
                    #"AFN": "", 
                    #"ALL": "",
                    #"AMD": "",
                    #"ANG": "",
                    #"AOA": "",
                    "ARS": "Argentine Peso",
                    "AUD": "Australian Dollar",
                    #"AWG": "",
                    #"AZN": "",
                    "BAM": "Bosnia-Herzegovina Convertible Mark",
                    #"BBD": "",
                    #"BDT": "",
                    "BGN": "Bulgarian Lev",
                    #"BHD": "",
                    #"BIF": "",
                    #"BMD": "",
                    #"BND": "",
                    #"BOB": "",
                    "BRL": "Brazilian Real",
                    #"BSD": "",
                    "BTC": "Bitcoin",
                    #"BTN": "",
                    #"BWP": "",
                    "BYN": "Belarusian Ruble",
                    #"BZD": "",
                    "CAD": "Canadian Dollar",
                    #"CDF": "",
                    "CHF": "Swiss Franc",
                    #"CLF": "",
                    "CLP": "Chilean Peso",
                    #"CNH": "",
                    "CNY": "Chinese Yuan",
                    "COP": "Colombian Peso",
                    #"CRC": "",
                    #"CUC": "",
                    "CUP": "Cuban Peso",
                    #"CVE": "",
                    "CZK": "Czech Koruna",
                    #"DJF": "",
                    "DKK": "Danish Krone",
                    #"DOP": "",
                    #"DZD": "",
                    "EGP": "Egyptian Pound",
                    #"ERN": "",
                    #"ETB": "",
                    "EUR": "Euro",
                    #"FJD": "",
                    #"FKP": "",
                    "GBP": "Pound Sterling",
                    #"GEL": "",
                    #"GGP": "",
                    #"GHS": "",
                    #"GIP": "",
                    #"GMD": "",
                    #"GNF": "",
                    #"GTQ": "",                 
                    #"GYD": "",
                    "HKD": "Hong Kong Dollar",
                    #"HNL": "",
                    "HRK": "Croatian Kuna",
                    #"HTG": "",
                    "HUF": "Hungarian Forint",
                    #"IDR": "",
                    "ILS": "Israeli New Shekel",
                    #"IMP": "",
                    "INR": "Indian Rupee",
                    "IQD": "Iraqi Dinar",
                    "IRR": "Iranian Rial",
                    "ISK": "Icelandic Króna",
                    #"JEP": "",
                    #"JMD": "",
                    #"JOD": "",
                    "JPY": "Japanese Yen",
                    #"KES": "",
                    #"KGS": "",
                    #"KHR": "",
                    #"KMF": "",
                    #"KPW": "",
                    "KRW": "South Korean Won",
                    #"KWD": "",
                    #"KYD": "",
                    "KZT": "Kazakhstani Tenge",
                    #"LAK": "",
                    #"LBP": "",
                    #"LKR": "",
                    #"LRD": "",
                    #"LSL": "",
                    #"LYD": "",
                    #"MAD": "",
                    #"MDL": "",
                    #"MGA": "",
                    "MKD": "Macedonian Denar",
                    #"MMK": "",
                    #"MNT": "",
                    #"MOP": "",
                    #"MRU": "",
                    #"MUR": "",
                    #"MVR": "",
                    #"MWK": "",
                    "MXN": "Mexican Peso",
                    #"MYR": "",
                    #"MZN": "",
                    #"NAD": "",
                    "NGN": "Nigerian Naira",
                    #"NIO": "",
                    "NOK": "Norwegian Krone",
                    #"NPR": "",
                    "NZD": "New Zealand Dollar",
                    #"OMR": "",
                    #"PAB": "",
                    "PEN": "Peruvian Sol",
                    #"PGK": "",
                    #"PHP": "",
                    #"PKR": "",
                    "PLN": "Poland Złoty",
                    #"PYG": "",
                    "QAR": "Qatari Rial",
                    "RON": "Romanian Leu",
                    "RSD": "Serbian Dinar",
                    "RUB": "Russian Ruble",
                    #"RWF": "",
                    "SAR": "Saudi Riyal",
                    #"SBD": "",
                    #"SCR": "",
                    #"SDG": "",
                    "SEK": "Swedish Krona",
                    "SGD": "Singapore Dollar",
                    #"SHP": "",
                    #"SLL": "",
                    #"SOS": "",
                    #"SRD": "",
                    #"SSP": "",
                    #"STD": "",
                    #"STN": "",
                    #"SVC": "",
                    #"SYP": "",
                    #"SZL": "",
                    "THB": "Thai Baht",
                    #"TJS": "",
                    #"TMT": "",
                    #"TND": "",
                    #"TOP": "",
                    "TRY": "Turkish Lira",
                    #"TTD": "",
                    #"TWD": "",
                    #"TZS": "",
                    "UAH": "Ukrainian Hryvnia",
                    #"UGX": "",
                    "USD": "United States Dollar",
                    #"UYU": "",
                    #"UZS": "",
                    "VES": "Venezuelan Bolívar",
                    "VND": "Vietnamese Dong",
                    #"VUV": "",
                    #"WST": "",
                    "XAF": "Central African CFA Franc",
                    "XAG": "Silver Ounce",
                    "XAU": "Gold Ounce"
                  }



all_currencies_list = ['AED', 'AFN', 'ALL', 'AMD',
'ANG', 'AOA', 'ARS', 'AUD', 'AWG', 'AZN', 'BAM',
'BBD', 'BDT', 'BGN', 'BHD', 'BIF', 'BMD', 'BND',
'BOB', 'BRL', 'BSD', 'BTC', 'BTN', 'BWP', 'BYN',
'BZD', 'CAD', 'CDF', 'CHF', 'CLF', 'CLP', 'CNH',
'CNY', 'COP', 'CRC', 'CUC', 'CUP', 'CVE', 'CZK',
'DJF', 'DKK', 'DOP', 'DZD', 'EGP', 'ERN', 'ETB',
'EUR', 'FJD', 'FKP', 'GBP', 'GEL', 'GGP', 'GHS',
'GIP', 'GMD', 'GNF', 'GTQ', 'GYD', 'HKD', 'HNL',
'HRK', 'HTG', 'HUF', 'IDR', 'ILS', 'IMP', 'INR',
'IQD', 'IRR', 'ISK', 'JEP', 'JMD', 'JOD', 'JPY',
'KES', 'KGS', 'KHR', 'KMF', 'KPW', 'KRW', 'KWD',
'KYD', 'KZT', 'LAK', 'LBP', 'LKR', 'LRD', 'LSL',
'LYD', 'MAD', 'MDL', 'MGA', 'MKD', 'MMK', 'MNT',
'MOP', 'MRU', 'MUR', 'MVR', 'MWK', 'MXN', 'MYR',
'MZN', 'NAD', 'NGN', 'NIO', 'NOK', 'NPR', 'NZD',
'OMR', 'PAB', 'PEN', 'PGK', 'PHP', 'PKR', 'PLN',
'PYG', 'QAR', 'RON', 'RSD', 'RUB', 'RWF', 'SAR',
'SBD', 'SCR', 'SDG', 'SEK', 'SGD', 'SHP', 'SLL',
'SOS', 'SRD', 'SSP', 'STD', 'STN', 'SVC', 'SYP',
'SZL', 'THB', 'TJS', 'TMT', 'TND', 'TOP', 'TRY',
'TTD', 'TWD', 'TZS', 'UAH', 'UGX', 'USD', 'UYU',
'UZS', 'VES', 'VND', 'VUV', 'WST', 'XAF', 'XAG',
'XAU', 'XCD', 'XDR', 'XOF', 'XPD', 'XPF', 'XPT',
'YER', 'ZAR', 'ZMW', 'ZWL']